### ISSUE TITLE
Do you have any another example for slot machines?

### ISSUE THREAD

**Issue by bshiroya** [meue/slotmachineBackend#1]
Dear Meue

Very helpful your code
We need another  reference if you have because you have a very good idea about the slot machine program 
any referenced document and link 
Do you have another example for slot machines?

Waiting for your replay 

Regards
Bhadresh

**Comment by bshiroya** [comment]
@meue need your help

**Comment by meue** [comment]
@bshiroya 
Hi Bhadresh,

thank you for your feedback and I am happy to hear that you find this code useful.
I would like to help you with your request but I am not sure how exactly I can serve you.
Could you be a little bit more specific?

Do you need a general overview about how slotmachines work in general?
Do you need documentation about the code?
Do you need a frontend?

Best,
Meue

**Comment by bshiroya** [comment]
@meue Thanks for quick replay  

Do you need a general overview about how slotmachines work in general?
=>Yes
Do you need documentation about the code?
=>Yes
Do you need a frontend?
=> Yes

Is there any logic behind bonus or wild symbol pay line matches?

**Comment by meue** [comment]
@bshiroya 
So you basically need everything to get a slotmachine up and running?

Right now there is no logic which handles wilds and bonus-symbols such as scatters.
To implement wild-symbols I suggest to take a look at Paytable:38.
I highly recommend to create some kind of a WinEvaluation-class and encapsulate the logic to avoid high complexity

Scatters are much harder because you need some feature to be triggered, like freegames.

Regarding frontend, I also have a fake-frontend which I might upload someday.. Maybe I take a look at it later.

Something in general:
I have been working in slotmachine business for many years in multiple companies and all I can say is that even if those games look simple and promise to make a lot of money it is serious business and there is a lot of work to be made.
If you have specific questions I am ready to help out but I am not here to create your slotmachine-business from scratch.

Best,
Meue

**Comment by bshiroya** [comment]
Hi @meue 
Can we connect?
skype: bhadresh.shiroya12

**Comment by bshiroya** [comment]
@meue Very helpful
